### ISSUE TITLE
When a widget is locked, prevent user action

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board#16]
When a widget is locked, the user cannot edit a widget. Show an overlay on the widget with black background and opacity, with a message on center "This widget is locked by Jean Dupont. Please wait."

**Comment by CremaFR** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/15933162/f0c785de-2e5e-11e6-8b2d-1a811b0c8b77.png)

But I still have some problems with this message "This widget is locked by Jean Dupont".

On small widgets it goes like that : 
![image](https://cloud.githubusercontent.com/assets/5360522/15933290/751a04ec-2e5f-11e6-8f9d-9ed5e15e5053.png)

So should I use media query or something to remove the text when the width is too small for the text or just remove the message and show only the lock icon and add a tooltip to see the name of who's locking the widget?

**Comment by thomaswinckell** [comment]
Read this : https://developer.mozilla.org/fr/docs/Web/CSS/Media_queries

Media queries are for apply a style for different **screen** size.

My solution is to put the text in the middle of the widget, with a black background with opacity on the whole widget. If the widget is too small, you can do an ellipsis.

Read more about ellipsis : https://developer.mozilla.org/fr/docs/Web/CSS/text-overflow
