### ISSUE TITLE
widget Twitter Timeline

### ISSUE THREAD

**Issue by CremaFR** [thomaswinckell/reactfire-white-board#24]

**Comment by CremaFR** [comment]
Nowadays twitter timelines are the old RSS feeds, right?

**Comment by CremaFR** [comment]
But we still need to put a twitter icon on the button. On the icomoon pack this one is missing and I'd like to import it on our theme. Do you remember how you created this icon pack?

**Comment by thomaswinckell** [comment]
Huh, yes, RSS is quite old (I never used it). Why do you want a widget like this ?! It's better to do a twitter feed widget. Yes, you go to the website of icomoon, you take all the material design icons and you take the icons that you want, and generate font and css.

**Comment by CremaFR** [comment]
I created this issue when someone came with this idea. But I made a twitter timeline instead. :-)

![image](https://cloud.githubusercontent.com/assets/5360522/17394189/1303de28-5a28-11e6-974e-e207980fe63f.png)

**Comment by CremaFR** [comment]
This widget is now done. I'm closing
