### ISSUE TITLE
Notifications styles

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board#4]
Please improve the notifications style. 

<img width="239" alt="screen shot 2016-05-30 at 14 13 05" src="https://cloud.githubusercontent.com/assets/5302702/15649279/aeba75d4-2670-11e6-85f7-42ceb639a51a.png">

Something like this maybe ?

![p12dgje](https://cloud.githubusercontent.com/assets/5302702/15649310/dacef456-2670-11e6-83ed-3b8b5e3365ac.png)

**Comment by thomaswinckell** [comment]
Maybe look at this since you don't like css :-P  
https://github.com/tomchentw/react-toastr

**Comment by CremaFR** [comment]
Is this one ok? http://igorprado.com/react-notification-system/

I used it on the website

**Comment by thomaswinckell** [comment]
👍

**Comment by CremaFR** [comment]
![image](https://cloud.githubusercontent.com/assets/5360522/16192492/f428a4a4-36e9-11e6-8e92-07116ffd5041.png)
