### ISSUE TITLE
Drawing tool : line width

### ISSUE THREAD

**Issue by thomaswinckell** [thomaswinckell/reactfire-white-board#7]
To select a line width, please use a Slider component. The values will be from 10 to 100 or something like this. It will be easier for the user than a text input.

**Comment by CremaFR** [comment]
I tried to use some modules to have a Slider component like this one : https://github.com/davidchin/react-input-range or this one https://github.com/react-component/slider

But my problem is they all require to import a .css file aswell and I'm struggling with it. 

ps : http://stackoverflow.com/questions/36209318/using-webpack-to-load-css-files-from-node-modules

**Comment by thomaswinckell** [comment]
What is your problem ? You don't know how to include it ? Or there is an error given by webpack like "You need a specific loader for this file type" ?

**Comment by CremaFR** [comment]
I don't know how to include it using webpack. The workaround to put the path in index.html works but won't work anymore when we'll export the module.

**Comment by thomaswinckell** [comment]
Include it in the theme (in the @global {  }  so it will be included without anonymizing the class names).
